version: 2.1
orbs:
  node: circleci/node@4.5.1
  gcp-cli: circleci/gcp-cli@2.1.0

jobs:
  run_tests:
    working_directory: ~/project
    docker:
      - image: circleci/node:12
    steps:
      - checkout:
          path: ~/project
      - node/install-packages:
          pkg-manager: yarn
      - run: yarn test

  build_deploy_hosting:
    working_directory: ~/project
    docker:
      - image: circleci/node:12
    steps:
      - checkout:
          path: ~/project
      - node/install-packages:
          pkg-manager: yarn
      - run: yarn build
      - when:
          condition:
            equal: [master, << pipeline.git.branch >>]
          steps:
            - run: yarn firebase deploy --only hosting --token "$FIREBASE_TOKEN"

workflows:
  ci:
    jobs:
      - run_tests
      - build_deploy_hosting
