app = "flightplot-jobs"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
NODE_OPTIONS = "--max-old-space-size=200"

[experimental]
allowed_public_ports = []
auto_rollback = true

[[services]]
auto_stop_machines = false
http_checks = []
processes = ["app"]
protocol = "tcp"
script_checks = []
[services.concurrency]
hard_limit = 25
soft_limit = 20
type = "connections"
