export default {
    AC: { description: 'Withdrawn for maintenance', shortPhraseo: 'Withdrawn for maint' },
    AD: { description: 'Available for daylight operation', shortPhraseo: 'avbl day ops' },
    AF: { description: 'Flight checked and found reliable', shortPhraseo: 'fltck okay' },
    AG: {
        description: 'Operating but ground checked only, awaiting flight chec',
        shortPhraseo: 'opr awaiting fltck',
    },
    AH: { description: 'Hours of service are now', shortPhraseo: 'Hr Serv' },
    AK: { description: 'Resumed normal operations', shortPhraseo: 'Okay' },
    AL: { description: 'Minimum usable flight level', shortPhraseo: 'mnm usable fl' },
    AM: { description: 'Military operations only', shortPhraseo: 'Mil Ops Only' },
    AN: { description: 'Available for night operation', shortPhraseo: 'Avalb Night Ops' },
    AO: { description: 'Operational', shortPhraseo: 'Ops' },
    AP: { description: 'Available, prior permission required', shortPhraseo: 'Avail ppr' },
    AR: { description: 'Available on request', shortPhraseo: 'Avalb OR' },
    AS: { description: 'Unserviceable', shortPhraseo: 'U/S' },
    AU: {
        description: 'Not available (specify reason if appropriate)',
        shortPhraseo: 'Not Availb',
    },
    AW: { description: 'Completely withdrawn', shortPhraseo: 'withdrawn' },
    AX: {
        description: 'Previously promulgated shutdown has been cancelled',
        shortPhraseo: 'promulgated shutdown cnl',
    },
    CA: { description: 'Activated', shortPhraseo: 'Act' },
    CC: { description: 'Completed', shortPhraseo: 'Complt' },
    CD: { description: 'Deactivated', shortPhraseo: 'Deactivated' },
    CE: { description: 'Erected', shortPhraseo: 'Erected' },
    CF: { description: 'Operating frequency(ies) changed to', shortPhraseo: 'Freq changed' },
    CG: { description: 'Downgraded to', shortPhraseo: 'Downgraded to' },
    CH: { description: 'Changed', shortPhraseo: 'Changed' },
    CI: {
        description: 'Identification or radio call sign changed to',
        shortPhraseo: 'Ident change',
    },
    CL: { description: 'Realigned', shortPhraseo: 'Realigned' },
    CM: { description: 'Displaced', shortPhraseo: 'Displaced' },
    CN: { description: 'Cancelled', shortPhraseo: 'cnl' },
    CO: { description: 'Operating', shortPhraseo: 'opr' },
    CP: { description: 'Operating on reduced power', shortPhraseo: 'opr reduced pwr' },
    CR: { description: 'Temporarily replaced by', shortPhraseo: 'Tempo rplcd by' },
    CS: { description: 'Installed', shortPhraseo: 'Installed' },
    CT: { description: 'On test, do not use', shortPhraseo: 'On test, do not use' },
    HA: { description: 'Braking action is', shortPhraseo: 'BA is' },
    'HA1 HA2 HA3 HA4 HA5': {
        description: '1-Poor 2-Medium poor 3-Medium 4-Medium good 5-Good',
        shortPhraseo: '1-Poor 2-Medium poor 3-Medium 4-Medium good 5-Good',
    },
    HB: {
        description: 'Braking coefficient is ... (specify measurement device used)',
        shortPhraseo: 'brkg coefficient is',
    },
    HC: {
        description: 'Covered by compacted snow to depth of x Ft',
        shortPhraseo: 'cov compacted snow depth',
    },
    HD: {
        description: 'Covered by dry snow to a depth of x Ft',
        shortPhraseo: 'cov dry snow depth',
    },
    HE: {
        description: 'Covered by water to a depth of x Ft',
        shortPhraseo: 'cov water depth',
    },
    HF: { description: 'Totally free of snow and ice', shortPhraseo: 'Free of snow and ice' },
    HG: { description: 'Grass cutting in progress', shortPhraseo: 'Grass cutting' },
    HH: { description: 'Hazard due to (specify)', shortPhraseo: 'Hazard due' },
    HI: { description: 'Covered by ice', shortPhraseo: 'Cov ice' },
    HJ: {
        description:
            'Launch planned ... (specify balloon flight identification or project Code name, launch site, planned period of launch(es)_date/time, expected climb direction, estimate time to pass 18,000 m (60,000 ft), together with estimated location)',
        shortPhraseo: 'Launch plan',
    },
    HK: { description: 'Migration in progress', shortPhraseo: 'Migration inPr' },
    HL: { description: 'Snow clearance completed', shortPhraseo: 'snow clr cmpl' },
    HM: { description: 'Marked by', shortPhraseo: 'Marked by' },
    HN: {
        description: 'Covered by wet snow or slush to a depth of x Ft',
        shortPhraseo: 'cov wet snow depth',
    },
    HO: { description: 'Obscured by snow', shortPhraseo: 'Obscured by snow' },
    HP: { description: 'Snow clearance in progress', shortPhraseo: 'snow clr inpr' },
    HQ: {
        description:
            'Operation cancelled ... (specify balloon flight identification or project Code name)',
        shortPhraseo: 'OPR CNL',
    },
    HR: { description: 'Standing water', shortPhraseo: 'Standing water' },
    HS: { description: 'Sanding in progress', shortPhraseo: 'Sanding' },
    HT: {
        description: 'Approach according to signal area only',
        shortPhraseo: 'Apprch according signal area only',
    },
    HU: {
        description:
            'Launch in progress ... (specify balloon flight identification or project Code name, launch site, date/time of launch(es), estimated time passing 18,000 m (60,000 ft), or reaching cruising level if at or below 18,000 m (60,000 ft), together with estimated location, estimated date/time of termination of the flight, and planned location of ground contact when applicable)',
        shortPhraseo: 'launch inpr',
    },
    HV: { description: 'Work completed', shortPhraseo: 'Worl compl' },
    HW: { description: 'Work in progress', shortPhraseo: 'WIP' },
    HX: { description: 'Concentration of birds', shortPhraseo: 'Bird concentration' },
    HY: { description: 'Snow banks exist (specify height)', shortPhraseo: 'Snow banks HGT' },
    HZ: {
        description: 'Covered by frozen ruts and ridges',
        shortPhraseo: 'cov frozen ruts and ridges',
    },
    LA: {
        description: 'Operating on APU (Auxiliary Power Supply)',
        shortPhraseo: 'OPR AUX PWR',
    },
    LB: {
        description: 'Reserved for aircraft based therein',
        shortPhraseo: 'Reserved for acft based therein',
    },
    LC: { description: 'Closed', shortPhraseo: 'clsd' },
    LD: { description: 'Unsafe', shortPhraseo: 'Unsafe' },
    LE: {
        description: 'Operated without auxiliary power supply',
        shortPhraseo: 'OPER withou AUX PWR',
    },
    LF: { description: 'Interference from', shortPhraseo: 'Interference from' },
    LG: {
        description: 'Operating without identification',
        shortPhraseo: 'OPR without IDENT',
    },
    LH: {
        description: 'Unserviceable for aircraft heavier than',
        shortPhraseo: 'U/S for acft heavier than',
    },
    LI: { description: 'Close to IFR operations', shortPhraseo: 'Clsd IFR OPS' },
    LK: { description: 'Operating as a fixed light', shortPhraseo: 'OPR as F LGT' },
    LL: {
        description: 'Usable for lenght of... and width of...',
        shortPhraseo: 'usable lenght/width',
    },
    LN: { description: 'Close to all night operations', shortPhraseo: 'CLSD Night OPS' },
    LP: { description: 'Prohibited to', shortPhraseo: 'Prohibited to' },
    LR: {
        description: 'Aircraft restricted to runways and taxiways',
        shortPhraseo: 'ACFT restricted to RWY and TWY',
    },
    LS: { description: 'Subject to interruption', shortPhraseo: 'Subj intrp' },
    LT: { description: 'Limited to', shortPhraseo: 'Limited to' },
    LV: { description: 'Close to VFR operations', shortPhraseo: 'CLSD VFR OPS' },
    LW: { description: 'Will take place', shortPhraseo: 'Will take place' },
    LX: {
        description: 'Operating but caution advised to',
        shortPhraseo: 'OPS but caution due',
    },
    TT: { description: 'Trigger NOTAM', shortPhraseo: 'tt' },
    XX: {
        description:
            'Where 4th and 5th letter Code does not cover the situation, use XX and supplement by plain language',
        shortPhraseo: '(plain language following the NOTAM Code)',
    },
    KK: {
        description: 'Checklist',
        shortPhraseo: 'Checklist',
    },
};
