export default {
    AA: {
        description: 'Minimum altitude (specify en route/crossing/safe)',
        shortPhraseo: 'mnm alt',
    },
    AC: { description: 'Class B, C, D, or E Surface Area', shortPhraseo: 'CTR' },
    AD: { description: 'Air defense identification zone (ADIZ)', shortPhraseo: 'ADIZ' },
    AE: { description: 'Control area (CTA)', shortPhraseo: 'CTA' },
    AF: { description: 'Flight information region (FIR)', shortPhraseo: 'FIR' },
    AH: { description: 'Upper control area (UTA)', shortPhraseo: 'UTA' },
    AL: { description: 'Minimum usable flight level', shortPhraseo: 'mnm usable FL' },
    AN: { description: 'Area navigation route', shortPhraseo: 'Rnav route' },
    AO: { description: 'Oceanic control area (OCA)', shortPhraseo: 'OCA' },
    AP: {
        description: 'Reporting point (specify name or Coded designator)',
        shortPhraseo: 'Rep',
    },
    AR: { description: 'ATS route (specify)', shortPhraseo: 'ATS route' },
    AT: { description: 'Class B Airspace', shortPhraseo: 'TMA' },
    AU: { description: 'Upper flight information region (UIR)', shortPhraseo: 'UIR' },
    AV: { description: 'Upper advisory area (UDA)', shortPhraseo: 'UDA' },
    AX: { description: 'Intersection (INT)', shortPhraseo: 'INT' },
    AZ: { description: 'Aerodrome traffic zone (ATZ)', shortPhraseo: 'ATZ' },
    CA: {
        description: 'Air/ground (specify service and frequency)',
        shortPhraseo: 'a/g fac',
    },
    CB: {
        description: 'Automatic dependent surveillance — broadcast (details)',
        shortPhraseo: 'ads-b',
    },
    CC: {
        description: 'Automatic dependent surveillance — contract (details)',
        shortPhraseo: 'ads-c',
    },
    CD: {
        description: ' Controller-pilot data link communications (details)',
        shortPhraseo: 'cpdlc',
    },
    CE: { description: 'En route surveillance radar', shortPhraseo: 'RSR' },
    CG: { description: 'Ground controlled approach system (GCA)', shortPhraseo: 'GCA' },
    CL: { description: 'Selective calling system (SELCAL)', shortPhraseo: 'SELCAL' },
    CM: { description: 'Surface movement radar', shortPhraseo: 'SMR' },
    CP: {
        description: 'Precision approach radar (PAR) (specify runway)',
        shortPhraseo: 'PAR',
    },
    CR: {
        description:
            'Surveillance radar element of precision approach radar system (specify wavelength)',
        shortPhraseo: 'SRE',
    },
    CS: { description: 'Secondary surveillance radar (SSR)', shortPhraseo: 'SSR' },
    CT: { description: 'Terminal area surveillance radar (TAR)', shortPhraseo: 'TAR' },
    FA: { description: 'Aérodrome', shortPhraseo: 'AD' },
    FB: {
        description: 'Braking action measurement equipment (specify type)',
        shortPhraseo: 'BA measurement eqpt',
    },
    FC: {
        description: 'Ceiling measurement equipment',
        shortPhraseo: 'Ceiling measurement equip',
    },
    FD: {
        description: 'Docking system (specify AGNIS, BOLDS, etc.)',
        shortPhraseo: 'Dckg system',
    },
    FF: { description: 'Fire fighting and rescue', shortPhraseo: 'Fire & Rescue' },
    FG: { description: 'Ground movement control', shortPhraseo: 'GND MV CTL' },
    FH: {
        description: 'Helicopter alighting area/platform',
        shortPhraseo: 'Hel alighting area',
    },
    FL: { description: 'Landing direction indicator', shortPhraseo: 'LDI' },
    FM: { description: 'Meteorological service (specify type)', shortPhraseo: 'MET' },
    FO: { description: 'Fog dispersal system', shortPhraseo: 'Fog dispersal' },
    FP: { description: 'Heliport', shortPhraseo: 'Heliport' },
    FS: { description: 'Snow removal equipment', shortPhraseo: 'Snow removal equip' },
    FT: {
        description:
            'Transmissometer (specify runway and, where applicable, designator(s) of transmissometer(s))',
        shortPhraseo: 'Transmissometer',
    },
    FU: { description: 'Fuel availability', shortPhraseo: 'Fuel Avalb' },
    FW: { description: 'Wind direction indicator', shortPhraseo: 'WDI' },
    FZ: { description: 'Customs', shortPhraseo: 'Cust' },
    GA: {
        description: 'GNSS airfield-specific operations (specify operation)',
        shortPhraseo: 'gnss airfield',
    },
    GW: {
        description: 'GNSS area-wide operations (specify operation)',
        shortPhraseo: 'gnss area',
    },
    IC: { description: 'Instrument landing system', shortPhraseo: 'ILS' },
    ID: { description: 'DME associated with ILS', shortPhraseo: 'ILS DME' },
    IG: { description: 'Glide path (ILS) (specify runway)', shortPhraseo: 'ILS GP' },
    II: { description: 'Inner marker (ILS) (specify runway)', shortPhraseo: 'ILS IM' },
    IL: { description: 'Localizer (ILS) (specify runway)', shortPhraseo: 'ILS LIZ' },
    IM: { description: 'Middle marker (ILS) (specify runway)', shortPhraseo: 'ILS MM' },
    IO: { description: 'Outer marker (ILS) (specify runway)', shortPhraseo: 'ILS OM' },
    IS: { description: 'ILS Category I (specify runway)', shortPhraseo: 'ILS I' },
    IT: { description: 'ILS Category II (specify runway)', shortPhraseo: 'ILS II' },
    IU: { description: 'ILS Category III (specify runway)', shortPhraseo: 'ILS III' },
    IW: {
        description: 'Microwave landing system (MLS) (specify runway)',
        shortPhraseo: 'MLS',
    },
    IX: { description: 'Locator, outer (ILS) (specify runway)', shortPhraseo: 'ILS LO' },
    IY: { description: 'Locator, middle (ILS) (specify runway)', shortPhraseo: 'ILS LM' },
    LA: {
        description: 'Approach lighting system (specify runway and type)',
        shortPhraseo: 'apch light',
    },
    LB: { description: 'Airport beacon', shortPhraseo: 'abn' },
    LC: {
        description: 'Runway center line lights (specify runway)',
        shortPhraseo: 'rwy centreline light',
    },
    LD: { description: 'Landing direction indicator lights', shortPhraseo: 'Ldg light' },
    LE: {
        description: 'Runway edge lights (specify runway)',
        shortPhraseo: 'Rwy edge light',
    },
    LF: {
        description: 'Sequenced flashing lights (specify runway)',
        shortPhraseo: 'Sequenced flash light',
    },
    LG: {
        description: 'Pilot-controlled lighting',
        shortPhraseo: 'Pilot controlled lighting',
    },
    LH: {
        description: 'High intensity runway lights (specify runway)',
        shortPhraseo: 'High Inst rwy light',
    },
    LI: {
        description: 'Runway alignment indicator lights (specify runway)',
        shortPhraseo: 'Rwy align indicator light',
    },
    LK: {
        description: 'Category II components of approach lighting system (specify runway)',
        shortPhraseo: 'category II components apch light',
    },
    LL: {
        description: 'Low intensity runway lights (specify runway)',
        shortPhraseo: 'Low intens rwy light',
    },
    LM: {
        description: 'Medium intensity runway lights (specify runway)',
        shortPhraseo: 'Medium intens rwy light',
    },
    LP: {
        description: 'Precision approach path indicator (PAPI) (specify runway)',
        shortPhraseo: 'PAPI',
    },
    LR: {
        description: 'All landing area lighting facilities',
        shortPhraseo: 'landing area light fac',
    },
    LS: { description: 'Stopway lights (specify runway)', shortPhraseo: 'SWY light' },
    LT: { description: 'Threshold lights (specify runway)', shortPhraseo: 'Thres light' },
    LV: {
        description: 'Visual approach slope indicator system (specify type and runway)',
        shortPhraseo: 'VASIS',
    },
    LW: { description: 'Heliport lighting', shortPhraseo: 'Heli light' },
    LX: {
        description: 'Taxiway center line lights (specify taxiway)',
        shortPhraseo: 'twy centerline light',
    },
    LY: {
        description: 'Taxiway edge lights (specify taxiway)',
        shortPhraseo: 'twy edge light',
    },
    LZ: {
        description: 'Runway touchdown zone lights (specify runway)',
        shortPhraseo: 'Rwy Tdz light',
    },
    MA: { description: 'Movement area', shortPhraseo: 'Mov area' },
    MB: {
        description: 'Bearing strength (specify part of landing area or movement area)',
        shortPhraseo: 'bearing strengh',
    },
    MC: { description: 'Clearway (specify runway)', shortPhraseo: 'cwy' },
    MD: { description: 'Declared distances (specify runway)', shortPhraseo: 'deckared rwy' },
    MG: { description: 'Taxiing guidance system', shortPhraseo: 'tax guidance system' },
    MH: {
        description: 'Runway arresting gear (specify runway)',
        shortPhraseo: 'rwy arst gear',
    },
    MK: { description: 'Parking area', shortPhraseo: 'parkg area' },
    MM: {
        description: 'Daylight markings (specify threshold, centre line, etc.)',
        shortPhraseo: 'day markings',
    },
    MN: { description: 'Apron', shortPhraseo: 'Apron' },
    MP: { description: 'Aircraft stands (specify)', shortPhraseo: 'Acft stands' },
    MR: { description: 'runway specify runway)', shortPhraseo: 'rwy' },
    MS: { description: 'Stopway (specify runway)', shortPhraseo: 'swy' },
    MT: { description: 'Threshold (specify runway)', shortPhraseo: 'Thr' },
    MU: {
        description: 'Runway turning bay (specify runway)',
        shortPhraseo: 'Runway turning bay',
    },
    MW: { description: 'Strip (specify runway)', shortPhraseo: 'Strip' },
    MX: { description: 'Taxiway(s) (specify)', shortPhraseo: 'Twy' },
    NA: {
        description: 'All radio navigation facilities (except...)',
        shortPhraseo: 'All RDO NAV FAC',
    },
    NB: { description: 'Non directional beacon', shortPhraseo: 'NDB' },
    NC: { description: 'DECCA)', shortPhraseo: 'DECCA' },
    ND: { description: 'Distance measuring equipment (DME)', shortPhraseo: 'DME' },
    NF: { description: 'Fan marker', shortPhraseo: 'Fan mkr' },
    NL: { description: 'Locator (specify identification)', shortPhraseo: 'L' },
    NM: { description: 'VOR/DME', shortPhraseo: 'VOR/DME' },
    NN: { description: 'TACAN', shortPhraseo: 'TACAN' },
    NO: { description: 'OMEGA', shortPhraseo: 'OMEGA' },
    NT: { description: 'VORTAC', shortPhraseo: 'VORTAC' },
    NV: { description: 'VOR', shortPhraseo: 'VOR' },
    NX: {
        description: 'Direction finding station (specify type and frequency)',
        shortPhraseo: 'DF',
    },
    OA: { description: 'Aeronautical information service', shortPhraseo: 'AIS' },
    OB: { description: 'Obstacle (specify details)', shortPhraseo: 'obs' },
    OE: { description: 'Aircraft entry requirements', shortPhraseo: 'Acft entry Rqmnts' },
    OL: { description: 'Obstacle lights on ... (specify)', shortPhraseo: 'obs Lgt' },
    OR: { description: 'Rescue coordination centre', shortPhraseo: 'RCC' },
    PA: {
        description: 'Standard instrument arrival (STAR) (specify route designator)',
        shortPhraseo: 'STAR',
    },
    PD: {
        description: 'Standard instrument departure (SID) (specify route designator)',
        shortPhraseo: 'SID',
    },
    PF: { description: 'Flow control procedure', shortPhraseo: 'Flow ctl procedure' },
    PH: { description: 'Holding procedure', shortPhraseo: 'Hold proc' },
    PI: {
        description: 'Instrument approach procedure (specify type and runway)',
        shortPhraseo: 'inst apch proc',
    },
    PL: { description: 'Obstacle clearance limit (specify procedure)', shortPhraseo: 'OCL' },
    PM: {
        description: 'Aerodrome operating minima (specify procedure and amended minimum)',
        shortPhraseo: 'opr minima',
    },
    PO: { description: 'Obstacle clearance altitude', shortPhraseo: 'OCA' },
    PP: { description: 'Obstacle clearance height', shortPhraseo: 'OCH' },
    PR: { description: 'Radio failure procedure', shortPhraseo: 'Radio failure proc' },
    PT: { description: 'Transition altitude', shortPhraseo: 'Transition alt' },
    PU: {
        description: 'Missed approach procedure (specify runway)',
        shortPhraseo: 'Missed appch proc',
    },
    PX: {
        description: 'Minimum holding altitude (specify fix)',
        shortPhraseo: 'mnm holdg alt',
    },
    PZ: { description: 'ADIZ procedure', shortPhraseo: 'ADIZ proc' },
    RA: {
        description: 'Airspace reservation (specify)',
        shortPhraseo: 'Airspace reservation',
    },
    RD: {
        description: 'Danger area (specify national prefix and number)',
        shortPhraseo: 'D',
    },
    RO: { description: 'Overflying of ... (specify)', shortPhraseo: 'Overflying' },
    RP: {
        description: 'Prohibited area (specify national prefix and number)',
        shortPhraseo: 'P',
    },
    RR: {
        description: 'Restricted area (specify national prefix and number)',
        shortPhraseo: 'R',
    },
    RT: { description: 'Temporary restricted area', shortPhraseo: 'Tempo restricted' },
    SA: {
        description: 'Automatic terminal information service (ATIS)',
        shortPhraseo: 'ATIS',
    },
    SB: { description: 'ATS reporting office', shortPhraseo: 'ARO' },
    SC: { description: 'Area control centre (ACC)', shortPhraseo: 'ACC' },
    SE: { description: 'Flight information service (FIS)', shortPhraseo: 'FIS' },
    SF: { description: 'Airport flight information service (AFIS)', shortPhraseo: 'AFIS' },
    SL: { description: 'Flow control centre', shortPhraseo: 'Flow Ctl Centre' },
    SO: { description: 'Oceanic area control centre (OAC)', shortPhraseo: 'OAC' },
    SP: { description: 'Approach control service (APP)', shortPhraseo: 'APP' },
    SS: { description: 'Flight service station (FSS)', shortPhraseo: 'FSS' },
    ST: { description: 'Airport control tower (TWR)', shortPhraseo: 'TWR' },
    SU: { description: 'Upper area control centre (UAC)', shortPhraseo: 'UAC' },
    SV: { description: 'VOLMET broadcast', shortPhraseo: 'VOLMET' },
    SY: { description: 'Upper advisory service (specify)', shortPhraseo: 'Advisory ser' },
    WA: { description: 'Air display', shortPhraseo: 'Air display' },
    WB: { description: 'Aerobatics', shortPhraseo: 'Aerobatics' },
    WC: { description: 'Captive balloon or kite', shortPhraseo: 'Captive balloon or kite' },
    WD: { description: 'Demolition of explosives', shortPhraseo: 'Demolition of explosives' },
    WE: { description: 'Exercises (specify)', shortPhraseo: 'EXER' },
    WF: { description: 'Air refueling', shortPhraseo: 'Air refueling' },
    WG: { description: 'Glider flying', shortPhraseo: 'Glider flying' },
    WJ: { description: 'Banner/target towing', shortPhraseo: 'Banner/target towing' },
    WL: { description: 'Ascent of free balloon', shortPhraseo: 'Ascent of free balloon' },
    WM: { description: 'Missile, gun or rocket firing', shortPhraseo: 'FRMG' },
    WP: { description: 'Parachute jumping exercise (PJE)', shortPhraseo: 'PJE' },
    WS: { description: 'Burning or blowing gas', shortPhraseo: 'Burning or blowing gas' },
    WT: { description: 'Mass movement of aircraft', shortPhraseo: 'Mass Mov ACFT' },
    WU: { description: 'Unmanned aircraft', shortPhraseo: 'ua' },
    WV: { description: 'Formation flight', shortPhraseo: 'Formation flt' },
    WW: {
        description: 'Significant volcanic activity',
        shortPhraseo: 'significant volcanic act',
    },
    WZ: { description: 'model flying', shortPhraseo: 'model flying' },
    XX: {
        description:
            'Where 2nd and 3rd letter Code does not cover the situation, use XX and supplement by plain language',
        shortPhraseo: '(plain language following the NOTAM Code)',
    },
    KK: {
        description: 'Checklist',
        shortPhraseo: 'Checklist',
    },
};
