name: ci

on:
  - push

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
jobs:
  test:
    name: yarn test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd remix && yarn test
