name: ci

on:
  - push

defaults:
  run:
    working-directory: remix

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

jobs:
  test:
    name: yarn test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: npm install (library)
        uses: bahmutov/npm-install@v1
        with:
          working-directory: remix
      - run: npm run icons
      - run: npm run test

  deploy-preview:
    env:
      FIREBASE_SERVICE_ACCOUNT_KEY: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_FLIGHTPLOT_WEB }}
      SESSION_SECRET: ${{ secrets.SESSION_SECRET }}
      PR_NUMBER: ${{ github.event.number }}
    name: Deploy preview environment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: install myke
        run: |
          wget -qO /usr/local/bin/myke https://github.com/omio-labs/myke/releases/download/v1.0.2/myke_linux_amd64
          chmod +x /usr/local/bin/myke
          myke --version
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: myke deploy-preview
