name: ci

on:
  - push

defaults:
  run:
    working-directory: remix

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

jobs:
  test:
    name: yarn test
    runs-on: ubuntu-latest
    env:
      FORCE_COLOR: true
    steps:
      - uses: actions/checkout@v2
      - name: npm install (library)
        uses: bahmutov/npm-install@v1
        with:
          working-directory: remix
      - run: npm run icons
      - run: npm run test
