name: Deploy
on:
  push:
    branches:
      - master
      - remix-stashed

defaults:
  run:
    working-directory: remix

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
jobs:
  deploy:
    name: Deploy fly.io
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: npm run deploy -- --remote-only
