name: Pull Request Closed

on:
  pull_request_target:
    types:
      - closed

defaults:
  run:
    working-directory: remix

jobs:
  delete-preview:
    env:
      FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
      DEPLOYMENT_NAME: ${{ github.head_ref }}
    name: Delete preview environment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install myke
        run: |
          wget -qO /usr/local/bin/myke https://github.com/omio-labs/myke/releases/download/v1.0.2/myke_linux_amd64
          chmod +x /usr/local/bin/myke
          myke --version
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: myke destroy-preview
