on:
  pull_request:

defaults:
  run:
    working-directory: remix

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

jobs:
  deploy-preview:
    if: github.ref != 'refs/heads/master'
    env:
      FIREBASE_SERVICE_ACCOUNT_KEY: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_FLIGHTPLOT_WEB }}"
      SESSION_SECRET: ${{ secrets.SESSION_SECRET }}
      DEPLOYMENT_NAME: ${{ github.ref_name }}
    name: Deploy preview environment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install myke
        run: |
          wget -qO /usr/local/bin/myke https://github.com/omio-labs/myke/releases/download/v1.0.2/myke_linux_amd64
          chmod +x /usr/local/bin/myke
          myke --version
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: myke deploy-preview
