name: Pull Request (Re-)Opened & Updated

on:
  pull_request_target:

defaults:
  run:
    working-directory: remix

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

jobs:
  deploy-preview:
    if: github.ref != 'refs/heads/master'
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    env:
      FIREBASE_SERVICE_ACCOUNT_KEY: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_FLIGHTPLOT_WEB }}"
      SESSION_SECRET: ${{ secrets.SESSION_SECRET }}
      DEPLOYMENT_NAME: ${{ github.head_ref }}
    name: Deploy preview environment
    steps:
      - uses: actions/checkout@v2
      - name: install myke
        run: |
          wget -qO /usr/local/bin/myke https://github.com/omio-labs/myke/releases/download/v1.0.2/myke_linux_amd64
          chmod +x /usr/local/bin/myke
          myke --version
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: myke deploy-preview
      - uses: mshick/add-pr-comment@v2
        with:
          message: |
            ✅ Preview environment deployed at https://flightplot-preview-${{ github.head_ref }}.fly.dev/
          message-failure: |
            ❌ Preview environment deployment failed.
